# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: journal_entry.proto

require 'google/protobuf'


descriptor_data = "\n\x13journal_entry.proto\x12\x07journal\"m\n\x0cJournalEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05\x64\x65\x62it\x18\x05 \x01(\x01\x12\x0e\n\x06\x63redit\x18\x06 \x01(\x01\"@\n\x16JournalEntriesResponse\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.journal.JournalEntryb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Journal
  JournalEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("journal.JournalEntry").msgclass
  JournalEntriesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("journal.JournalEntriesResponse").msgclass
end
